config/routes.rb
SportleMini::Application.routes.draw do
  resources :schedules

  root :to => "schedules#index"

end

app/models/item.rb
class Item
  attr_accessor :text, :inner, :outer, :level, :distance
  def initialize(params={})
    params.each do |key, value|
      send("#{key}=", value)
    end
  end

  def full_distance
    i = (self.inner == nil) ? 1 : self.inner
    o = (self.outer == nil) ? 1 : self.outer
    self.distance * i * o
  end
end

app/models/parser.rb
class Parser
  def self.parseSchedule(text, return_items = false)
    tItems = text.split(/\r|\n/).delete_if{|i| i == ""}
    items = tItems.map{|i| parseItem(i.chomp)}.compact
    if return_items
      items
    else
      {:full_distance => full_schedule_distance(items), :items => items.length}
    end
  end

  def self.parseItem(text)
    re = /^#{LEVEL}#{MULTI}#{MULTI}#{DIST}/i
    parse = re.match text
    return nil if parse.nil?
    item = Item.new(:text => text)
    case parse[1].length
    when 0
      item.level = 0
      item.outer = parse[3].to_i unless parse[3].nil?
      item.inner = parse[6].to_i unless parse[6].nil?
    when 1,2
      item.level = 1
      item.outer = nil
      item.inner = parse[3].to_i unless parse[3].nil?
    when 3,4
      item.level = 2
      item.outer = nil
      item.inner = nil
    end
    item.distance = parse[8].to_i unless parse[8].nil?
    return item
  end

  def self.full_schedule_distance(items)
    distance = 0
    last_outer = 1
    last_inner = 1
    for item in items
      if item.level == 0
        distance += item.full_distance
        last_outer = 1
        last_inner = 1
      elsif item.level == 1
        distance += item.full_distance * last_outer
        last_inner = 1
      elsif item.level == 2
        distance += item.full_distance * last_outer * last_inner
      end
      last_outer = item.outer unless (item.outer == nil)
      last_inner = item.inner unless (item.inner == nil)
    end
    return distance
  end

private
  MULTI = '((\d{1,2})(\*|x))?'
  DIST = '(\d+)($|\s|m$|m\s|m,\s)'
  LEVEL = '(\s{0,4})'
end

app/models/schedule.rb
class Schedule < RedisStorage::Model
  def self.attrs
    [ :id, :content, :long_course, :date, :created_at ]
  end
  attr_accessor *attrs
  validates :long_course, :inclusion => {:in => [true,false]}

  def long_course=(v)
    if !!v == v
      @long_course = v
    else
      @long_course = (v == "true")
    end
  end
  def date=(v)
    if v.class == Date
      @date = v
    else
      @date = Date.parse(v) unless v.nil?
    end
  end
  def created_at=(v)
    if v.class == Time
      @created_at = v
    else
      @created_at = Time.parse(v) unless v.nil?
    end
  end

  def previous
    keys = $db.smembers(self.class.persisted_key).sort
    i = keys.index("#{self.class.db_key}:#{id}")
    return nil if i == 0
    self.class.load(keys[i-1])
  end
  def next
    keys = $db.smembers(self.class.persisted_key).sort_by{|s| s.split(':')[1].to_i}
    i = keys.index("#{self.class.db_key}:#{id}")
    return nil if i == keys.length - 1
    self.class.load(keys[i+1])
  end
end

app/models/user.rb
class User < RedisStorage::Model
  include ActiveModel::SecurePassword
  has_secure_password
  validates_presence_of :password, :on => :create

  def self.attrs
    [ :id, :email, :password_digest ]
  end
  attr_accessor *attrs

  validate do
    errors.add(:email, "email is already taken") if $db.exists(email_key)
  end

  def self.find_by(key, value)
    return nil if key.nil? || value.nil? || key.to_sym != :email
    find_by_id($db.get("#{db_key}:#{key}:#{value}"))
  end

  def save
    unless persisted?
      @id = $db.incr(self.class.next_id_key)
    end
    if valid?
      $db.multi do
        $db.set db_key, to_json
        $db.set email_key, id
        #$db.set "#{self.class.db_key}:email:#{email}", id
        $db.sadd self.class.persisted_key, id
      end
      @id
    else
      nil
    end
  end

  def email_key
    "#{self.class.db_key}:email:#{email}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  http_basic_authenticate_with :name => "master", :password => "secret", :except => [:index, :show]
  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all.sort_by{|s| s.created_at}.reverse
    @newest = @schedules.first

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schedules.to_json }
      format.js
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule.to_json }
    end
  end

  # GET /schedules/new
  # GET /schedules/new.json
  def new
    @schedule = Schedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schedule.to_json }
    end
  end

  # GET /schedules/1/edit
  def edit
    @schedule = Schedule.find(params[:id])
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = ::Schedule.new(params[:schedule].merge('created_at' => Time.now))

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render json: @schedule.to_json, status: :created, location: @schedule }
        format.js { redirect_to schedules_path, notice: 'Schedule was successfully created.'}
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schedules/1
  # PUT /schedules/1.json
  def update
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email, params[:email]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ --> 
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
%head
  %meta{:charset=>"utf-8"}
  %title
    Sportle Mini
  %meta{:name=>"description", :content=>"app to store and share swim schedules"}
  %meta{:name=>"author", :content=>"sch1zo"}

  = stylesheet_link_tag    "application"
  = csrf_meta_tags
%body
  .container
    %nav
      %ul
        %li.first= link_to "random", Schedule.random
        - if @schedule
          %li= link_to_unless_current "previous", @schedule.previous
          %li= link_to 'view all schedules', schedules_path
          %li.last= link_to_unless_current "next", @schedule.next
    %div{:role => 'main'}
      = yield
    %footer

  = javascript_include_tag "application"

app/views/schedules/_form.html.haml
= form_for @schedule do |f|
  -if @schedule.errors.any?
    #error_explanation
      %h2= "#{pluralize(@schedule.errors.count, "error")} prohibited this schedule from being saved:"
      %ul
        - @schedule.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :long_course, "Course"
    = f.radio_button :long_course, true
    50m
    = f.radio_button :long_course, false
    25m
    =# f.check_box :long_course
  .field
    = f.label :date
    = f.text_field :date
  .actions
    = f.submit 'Save'

app/views/schedules/_schedule.html.haml
.content
  .info{:class => schedule.long_course == true ? "long" : "short"}
    = schedule.long_course == true ? "50m" : "25m"
    \|
    = schedule.date.strftime '%B %e %Y'
    \|
    = time_ago_in_words(schedule.created_at)
  .schedule
    = schedule.content.gsub("\n","<br/>").html_safe
  %ul.controls
    %li= link_to 'Edit', edit_schedule_path(schedule)
    %li= link_to 'Destroy', schedule, :confirm => 'Are you sure?', :method => :delete
    - if @schedules
      %li= link_to 'Show', schedule

app/views/schedules/edit.html.haml
%h1 Editing schedule

= render 'form'

= link_to 'Show', @schedule
\|
= link_to 'Back', schedules_path

app/views/schedules/index.html.haml
#schedules
  = render @schedules

= form_for Schedule.new, :remote => true do |f|
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :long_course, "Course"
    = f.radio_button :long_course, true
    50m
    = f.radio_button :long_course, false
    25m
  .field
    = f.label :date
    = f.text_field :date
  .actions
    = f.submit 'Save'

app/views/schedules/index.js.haml
=#!= "$('#schedules').html('#{escape_javascript(render(@schedules))}');"
!= "$('#schedules').prepend('#{escape_javascript(render(@newest))}');"
!= "$('#new_schedule')[0].reset();"
!= "$('#new_schedule')[1].reset();"
!= "$('#new_schedule')[2].reset();"

app/views/schedules/new.html.haml
%h1 New schedule

= render 'form'

= link_to 'Back', schedules_path

app/views/schedules/show.html.haml
- if notice
  %p#notice= notice

#schedules
  = render @schedule

app/views/users/new.html.haml
%h1
  Sign Up

= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2
        Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit